// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Frontend.Agents
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for CourseService.
    /// </summary>
    public static partial class CourseServiceExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<CourseMoment> FindAllCourseMoments(this ICourseService operations)
            {
                return Task.Factory.StartNew(s => ((ICourseService)s).FindAllCourseMomentsAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<CourseMoment>> FindAllCourseMomentsAsync(this ICourseService operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.FindAllCourseMomentsWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='courseMoments'>
            /// </param>
            public static UploadReport AddMultipleCourseMoments(this ICourseService operations, IList<CourseMoment> courseMoments = default(IList<CourseMoment>))
            {
                return Task.Factory.StartNew(s => ((ICourseService)s).AddMultipleCourseMomentsAsync(courseMoments), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='courseMoments'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<UploadReport> AddMultipleCourseMomentsAsync(this ICourseService operations, IList<CourseMoment> courseMoments = default(IList<CourseMoment>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.AddMultipleCourseMomentsWithHttpMessagesAsync(courseMoments, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='week'>
            /// </param>
            /// <param name='year'>
            /// </param>
            public static IList<CourseMoment> FindCourseMomentsInWeek(this ICourseService operations, int week, int year)
            {
                return Task.Factory.StartNew(s => ((ICourseService)s).FindCourseMomentsInWeekAsync(week, year), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='week'>
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<CourseMoment>> FindCourseMomentsInWeekAsync(this ICourseService operations, int week, int year, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.FindCourseMomentsInWeekWithHttpMessagesAsync(week, year, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
