// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Frontend.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CourseMoment
    {
        /// <summary>
        /// Initializes a new instance of the CourseMoment class.
        /// </summary>
        public CourseMoment() { }

        /// <summary>
        /// Initializes a new instance of the CourseMoment class.
        /// </summary>
        public CourseMoment(int? id = default(int?), Course course = default(Course), DateTime? startDate = default(DateTime?))
        {
            Id = id;
            Course = course;
            StartDate = startDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "course")]
        public Course Course { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDate")]
        public DateTime? StartDate { get; set; }

    }
}
