// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Frontend.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Course
    {
        /// <summary>
        /// Initializes a new instance of the Course class.
        /// </summary>
        public Course() { }

        /// <summary>
        /// Initializes a new instance of the Course class.
        /// </summary>
        public Course(string title = default(string), string code = default(string), int? durationInDays = default(int?))
        {
            Title = title;
            Code = code;
            DurationInDays = durationInDays;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "durationInDays")]
        public int? DurationInDays { get; set; }

    }
}
