// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Frontend.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UploadReport
    {
        /// <summary>
        /// Initializes a new instance of the UploadReport class.
        /// </summary>
        public UploadReport() { }

        /// <summary>
        /// Initializes a new instance of the UploadReport class.
        /// </summary>
        public UploadReport(int? amountInserted = default(int?), int? amountTotal = default(int?), int? amountOfDuplicates = default(int?), string fileName = default(string))
        {
            AmountInserted = amountInserted;
            AmountTotal = amountTotal;
            AmountOfDuplicates = amountOfDuplicates;
            FileName = fileName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amountInserted")]
        public int? AmountInserted { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amountTotal")]
        public int? AmountTotal { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amountOfDuplicates")]
        public int? AmountOfDuplicates { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

    }
}
