// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Frontend.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UploadReport
    {
        /// <summary>
        /// Initializes a new instance of the UploadReport class.
        /// </summary>
        public UploadReport() { }

        /// <summary>
        /// Initializes a new instance of the UploadReport class.
        /// </summary>
        public UploadReport(string label = default(string), string message = default(string), string fileName = default(string))
        {
            Label = label;
            Message = message;
            FileName = fileName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

    }
}
